#!python 3, pip install beautifulsoup4
import bs4, os
os.chdir(r"C:\Users\Piotr Jaroszuk\Desktop\python_kurs\Automate Boring Stuff\11 Web Scraping")
exampleFile = open('example.html')
exampleSoup = bs4.BeautifulSoup(exampleFile.read(), features="lxml")
print(exampleSoup)
elems = exampleSoup.select('#author')
print(type(elems))
print(len(elems))
print(type(elems[0]))
print(elems[0].getText())
print(str(elems[0]))
print(elems[0].attrs)

pElems = exampleSoup.select('p')
print(str(pElems[0]))
print(pElems[0].getText())
print(str(pElems[1]))
print(pElems[1].getText())
print(str(pElems[2]))
print(pElems[2].getText())
